# Generated by Django 5.1.2 on 2024-12-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_block_user", "can block user"), ("can_stop_mailing", "can stop mailing")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Токен"),
        ),
    ]
