# Generated by Django 5.1.2 on 2024-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_sending", models.DateTimeField(verbose_name="Дата и время первого отправления")),
                ("end_sending", models.DateTimeField(verbose_name="Дата и время окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("Создана", "Создана"), ("Запущена", "Запущена"), ("Завершена", "Завершена")],
                        default="Создана",
                        max_length=10,
                        verbose_name="Статус рассылки",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активность")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["first_sending"],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_attempt", models.DateTimeField(verbose_name="Дата и время попытки рассылки")),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        max_length=15,
                        verbose_name="Статус попытки",
                    ),
                ),
                ("server_response", models.TextField(max_length=150, verbose_name="Ответ почтового сервера")),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
                "ordering": ["date_attempt", "status"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("theme", models.CharField(max_length=255, verbose_name="Тема сообщения")),
                ("content", models.TextField(max_length=800, verbose_name="Содержание сообщения")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["theme"],
            },
        ),
        migrations.CreateModel(
            name="RecipientMailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=150, unique=True, verbose_name="Почта")),
                ("fio", models.CharField(max_length=150, verbose_name="Ф.И.О.")),
                ("comment", models.TextField(blank=True, max_length=255, null=True, verbose_name="Комментарий")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="mailing/photos", verbose_name="Фотография"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активность")),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
                "ordering": ["fio"],
            },
        ),
    ]
