# Generated by Django 5.1.2 on 2024-12-07 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Укажите получателей рассылки",
                related_name="recipients",
                to="mailing.recipientmailing",
                verbose_name="Получатели",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                    ("Отключена", "Отключена"),
                ],
                default="Создана",
                max_length=10,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="date_attempt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки рассылки"),
        ),
    ]
