# Generated by Django 5.1.2 on 2024-12-09 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_remove_mailing_is_active_alter_mailing_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_sending",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_sending",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время первого отправления"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                help_text="Выберите какое отправить сообщение",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
